site_name: Pygamii
pages:
- Pygamii: index.md
- Installation: install.md
- Tutorial:  
    - 'Create a Scene': 'tutorial/scene.md'
    - 'Add Objects': 'tutorial/create_objects.md'
    - 'Actions': 'tutorial/actions.md'
    - 'Collision': 'tutorial/collision.md'
- 'For Developers': dev.md
theme: readthedocs
repo_url: https://github.com/carlosmaniero/pygamii
